markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Springbeats Team Blog
url: http://blog.springbeats.com
description: A blog about the latest developments at Springbeats Inc.
logo: /images/logo.png
twitter: springbeats
facebook: springbeats.inc
youtube: SpringbeatsInc

links:
  -
    text: instinct
    link: http://try.springbeats.com
  -
    text: blog
    link: http://blog.springbeats.com
  -
    text: forum
    link: http://discuss.springbeats.com
  -
    text: academy
    link: http://www.springbeats.com/index.php/academy/academy/

